language: python

python:
  - "3.6"

env:
  - HOSTNAME=host1 AC_LOCATION=3rd

install:
  - pip install -r ac/requirements.txt

script:
  - pytest --cov=ac/ --cov-config=ac/tests/coverage.ini -c ac/tests/unit-pytest.ini
