- name: install lirc
  become: yes
  apt: pkg={{ item }} state=present
  with_items:
    - lirc

- name: /boot/config.txt
  become: yes
  ini_file:
    path: /boot/config.txt
    no_extra_spaces: yes
    section: null
    option: dtoverlay
    value: "lirc-rpi,gpio_in_pin={{ gpio_in_pin }},gpio_out_pin={{ gpio_out_pin }}"

- name: /etc/lirc/lirc_options.conf
  become: yes
  ini_file:
    path: /etc/lirc/lirc_options.conf
    section: lircd
    option: driver
    value: "default"

- name: /etc/lirc/lirc_options.conf
  become: yes
  ini_file:
    path: /etc/lirc/lirc_options.conf
    section: lircd
    option: device
    value: "/dev/lirc0"

- name: copy remote conf files
  become: yes
  template: src={{ item }} dest=/etc/lirc/lircd.conf.d
  with_fileglob:
    - '../templates/conf.d/*'

- name: stop lircd
  become: yes
  service: name=lircd state=stopped

- name: start lircd
  become: yes
  service: name=lircd state=started
