- name: install lirc
  become: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - lirc

- name: /boot/config.txt
  become: yes
  ini_file:
    path: /boot/config.txt
    no_extra_spaces: yes
    section: null
    option: dtoverlay
    value: "lirc-rpi,gpio_in_pin={{ gpio_in_pin }},gpio_out_pin={{ gpio_out_pin }}"

- name: /boot/config.txt
  become: yes
  ini_file:
    path: /boot/config.txt
    no_extra_spaces: yes
    section: null
    option: dtparam
    value: "i2c_arm=on"

- name: /etc/modules
  become: yes
  lineinfile:
    path: /etc/modules
    regexp: "^lirc_dev"
    line: "lirc_dev"

- name: /etc/modules
  become: yes
  lineinfile:
    path: /etc/modules
    regexp: "^lirc_rpi"
    insertafter: "^lirc_dev"
    line: "lirc_rpi gpio_in_pin={{ gpio_in_pin }} gpio_out_pin={{ gpio_out_pin }}"

- name: /etc/modules
  become: yes
  lineinfile:
    path: /etc/modules
    regexp: "^i2c-dev"
    line: "i2c-dev"

- name: /etc/lirc/hardware.conf
  become: yes
  ini_file:
    path: /etc/lirc/hardware.conf
    no_extra_spaces: yes
    section: null
    option: LIRCD_ARGS
    value: "\"--uinput\""

- name: /etc/lirc/hardware.conf
  become: yes
  ini_file:
    path: /etc/lirc/hardware.conf
    no_extra_spaces: yes
    section: null
    option: DRIVER
    value: "\"default\""

- name: /etc/lirc/hardware.conf
  become: yes
  ini_file:
    path: /etc/lirc/hardware.conf
    no_extra_spaces: yes
    section: null
    option: DEVICE
    value: "\"/dev/lirc0\""

- name: /etc/lirc/hardware.conf
  become: yes
  ini_file:
    path: /etc/lirc/hardware.conf
    no_extra_spaces: yes
    section: null
    option: MODULES
    value: "\"lirc_rpi\""

- name: copy lircd.conf
  become: yes
  template: src=lircd.conf dest=/etc/lirc/lircd.conf

- name: Ensures /etc/lirc/conf.d/ dir exists
  become: yes
  file: path=/etc/lirc/conf.d/ state=directory

- name: copy remote conf files
  become: yes
  template: src={{ item }} dest=/etc/lirc/conf.d/
  with_fileglob:
    - '../templates/conf.d/*'

- name: stop lirc
  become: yes
  service: name=lirc state=stopped

- name: start lirc
  become: yes
  service: name=lirc state=started
