- name: install lirc
  become: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - lirc

- name: /boot/config.txt
  become: yes
  ini_file:
    path: /boot/config.txt
    no_extra_spaces: yes
    section: null
    option: dtoverlay
    value: "lirc-rpi,gpio_in_pin={{ gpio_in_pin }},gpio_out_pin={{ gpio_out_pin }}"

- name: /etc/modules
  become: yes
  lineinfile:
    path: /etc/modules
    regexp: "^lirc_dev"
    line: "lirc_dev"

- name: /etc/modules
  become: yes
  lineinfile:
    path: /etc/modules
    regexp: "^lirc_rpi"
    insertafter: "^lirc_dev"
    line: "lirc_rpi gpio_in_pin={{ gpio_in_pin }} gpio_out_pin={{ gpio_out_pin }}"

- name: /etc/lirc/hardware.conf
  become: yes
  ini_file:
    path: /etc/lirc/hardware.conf
    no_extra_spaces: yes
    section: null
    option: LIRCD_ARGS
    value: "\"--uinput\""

- name: /etc/lirc/hardware.conf
  become: yes
  ini_file:
    path: /etc/lirc/hardware.conf
    no_extra_spaces: yes
    section: null
    option: DRIVER
    value: "\"default\""

- name: /etc/lirc/hardware.conf
  become: yes
  ini_file:
    path: /etc/lirc/hardware.conf
    no_extra_spaces: yes
    section: null
    option: DEVICE
    value: "\"/dev/lirc0\""

- name: /etc/lirc/hardware.conf
  become: yes
  ini_file:
    path: /etc/lirc/hardware.conf
    no_extra_spaces: yes
    section: null
    option: MODULES
    value: "\"lirc_rpi\""

#- name: copy lircd.conf file for ac_lg
#  become: yes
#  template: src=lircd_ac_lg.conf dest=/etc/lirc/lircd.conf.d/

- name: copy lircd.conf file for light
  become: yes
  template: src=lircd_light.conf dest=/etc/lirc/

- name: restart lirc
  become: yes
  service: name=lirc state=restarted
