---
- name: update apt
  become: yes
  apt: update_cache=yes cache_valid_time=3600

- name: install default packages
  become: yes
  apt: pkg={{ item }} state=present
  with_items:
    - ntp
    - vim
