---
- name: Setup raspberry pi
  hosts: all
  gather_facts: true

  roles:
  - {
      role: rpi_base
      user_name: "pi"
      user_password: ""
      HOSTNAME: ""
    }
  - {role: ir, gpio_in_pin: 15, gpio_out_pin: 14}
  - {role: photo_sensor}
  - {role: docker}
  - {
      role: ac,
      AC_LOCATION: "",
      AWS_ACCESS_KEY_ID: "",
      AWS_SECRET_ACCESS_KEY: "",
      SLACK_TOKEN: "",
      SLACK_URL: "",
    }
